---
title: "CLT problem"
author: "Dr. J"
date: "2022-10-22"
output: html_document
---


kkardashtemp  see code below

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(tidyverse)
require(lattice)
```

```{r}
Homers_data <- read.csv(file="Homers_data.csv")

my1000 <- sample(Homers_data , size = 1000, replace=T)

```

```{r}

library(ggplot2)
sampleNumber = sample(1:10000, size = 1000)
library(dplyr)
my1000 <- Homers_data[sampleNumber, ]
names(my1000)
# Basic density
p <- ggplot(my1000, aes(x=kkardashtemp)) + 
  geom_density()
p
# Add mean line
p+ geom_vline(aes(xintercept=mean(kkardashtemp)),
            color="blue", linetype="dashed", size=1)
print(paste('mean = ', mean(my1000$kkardashtemp),' sd = ',sd(my1000$kkardashtemp)))
```

```{r}
numb=2
Hdata = Homers_data[sample(1:1000, size=numb*1000, replace=T),"kkardashtemp"]
mdata  <-matrix(Hdata,nrow=1000,ncol=numb)
x.avg <- apply(mdata,1,mean)
my1000$k2 = x.avg

p <- ggplot(my1000, aes(x=k2)) + 
  geom_density() +

# Add mean line
  geom_vline(aes(xintercept=mean(k2)),
            color="blue", linetype="dashed", size=1)
print(paste('mean = ', mean(my1000$k2),' sd = ',sd(my1000$k2)))

```


```{r}
numb = 4
Hdata = Homers_data[sample(1:1000,size=numb*1000, replace=T),"kkardashtemp"]
mdata  <-matrix(Hdata,nrow=1000,ncol=numb)
x.avg <- apply(mdata,1,mean)
my1000$k4 = x.avg


p <- ggplot(my1000, aes(x=k4)) + 
  geom_density() +

# Add mean line
 geom_vline(aes(xintercept=mean(k4)),
            color="blue", linetype="dashed", size=1)
p + ggtitle("n = 4") +
  xlab("temperature") + ylab(" density")

print(paste('mean = ', mean(my1000$k4),' sd = ',sd(my1000$k4)))

```

```{r}
numb = 9
Hdata = Homers_data[sample(1:1000,size=numb*1000, replace=T),"kkardashtemp"]
mdata  <-matrix(Hdata,nrow=1000,ncol=numb)
x.avg <- apply(mdata,1,mean)
my1000$k9 = x.avg


p <- ggplot(my1000, aes(x=k9)) + 
  geom_density() +

# Add mean line
 geom_vline(aes(xintercept=mean(k9)),
            color="blue", linetype="dashed", size=1)
p + ggtitle("n = 9") +
  xlab("temperature") + ylab(" density")

print(paste('mean = ', mean(my1000$k9),' sd = ',sd(my1000$k9)))
```

```{r}
numb = 36
Hdata = Homers_data[sample(1:1000,size=numb*1000, replace=T),"kkardashtemp"]
mdata  <-matrix(Hdata,nrow=1000,ncol=numb)
x.avg <- apply(mdata,1,mean)
my1000$k36 = x.avg


p <- ggplot(my1000, aes(x=k36)) + 
  geom_density() +

# Add mean line
 geom_vline(aes(xintercept=mean(k36)),
            color="blue", linetype="dashed", size=1)
p + ggtitle("n = 36") +
  xlab("temperature") + ylab(" density")

print(paste('mean = ', mean(my1000$k36),' sd = ',sd(my1000$k36)))
```


